### ISSUE TITLE
Some questions regarding this project

### ISSUE THREAD

**Issue by Raj2032** [MoAlyousef/livid-rs#1]
Hi I have some questions regarding this project:

1. Can this be integrated into a game engine such as egui?
2. Is this similar to electron where it is a web application based?
3. Does it have the same performance as fltk?

**Comment by MoAlyousef** [comment]
1- Unfortunately no. Unless the game engine is web-based itself.
2- Yes. Except unlike Electron, this doesn't deploy its own instance of chromium, so install and deployment sizes are small. An advantage of electron though is that you can target a single backend (chromium) and be sure it would work the same everywhere. Webview on the other hand, has several backends (chromium and webkit), so there might be discrepancies between different backends.
3- Unfortunately no.

**Comment by Raj2032** [comment]
@MoAlyousef I see thanks mate
